### PR TITLE
Fix #6 - Handle trailing semicolons in Content-Type headers

### LINKED ISSUE #6: .net Core is strict when parsing Content-Type headers
As @LokiMidgard found out (https://github.com/lennykean/WcfCoreMtomEncoder/issues/1#issuecomment-555564872), .net Core is much more sensitive to errors while parsing `Content-Type` headers. I had the same issue as him when parsing a `Content-Type` header ending in a semicolon - this is not allowed by the specifications but it's still out there.

Example response by an infringing web server:
```
HTTP/1.1 200 OK
Date: Fri, 29 Nov 2019 17:04:04 GMT
Server: Apache
Content-Length: 3420
Connection: close
Content-Type: multipart/related; type="application/xop+xml"; boundary="uuid:f7b7667f-56cf-4cda-b2b2-9c7a12450a3a"; start="<root.message@cxf.apache.org>"; start-info="text/xml"

--uuid:f7b7667f-56cf-4cda-b2b2-9c7a12450a3a
Content-Type: application/xop+xml; charset=UTF-8; type="text/xml";
Content-Transfer-Encoding: binary
Content-ID: <root.message@cxf.apache.org>

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body>...</soap:Body></soap:Envelope>
--uuid:f7b7667f-56cf-4cda-b2b2-9c7a12450a3a
Content-Type: application/octet-stream
Content-Transfer-Encoding: binary
Content-ID: <fe00e1cb-f052-43ce-beab-477a0c58dbe1-48@cxf.apache.org>

<?xml version="1.0"?>
...
--uuid:f7b7667f-56cf-4cda-b2b2-9c7a12450a3a--
```

The first part's `Content-Type` header ends with a ";" and triggers an exception.

### PR DESCRIPTION
**Pull request by lscorcia**
Many implementations out there return a trailing semicolon in the Content-Type headers in multipart messages. Since .net core follows the specs and doesn't recognize them, the library does not deserialize them correctly. This pull request adds some code to make it more forgiving.

### CODE REVIEW

File: src/WcfCoreMtomEncoder/MtomPart.cs [hunk 1]
```diff
@@ -18,7 +18,20 @@ public MtomPart(HttpContent part)
...
 
-        public MediaTypeHeaderValue ContentType => _part.Headers.ContentType;
+        public MediaTypeHeaderValue ContentType
+        {
+            get
+            {
+                string contentTypeHeaderValue = _part.Headers.GetValues("Content-Type").FirstOrDefault();
+
+                MediaTypeHeaderValue parsedValue;
+                if (!String.IsNullOrEmpty(contentTypeHeaderValue) && MediaTypeHeaderValue.TryParse(contentTypeHeaderValue.TrimEnd(';'), out parsedValue))
```
Comment (lennykean) [inline src/WcfCoreMtomEncoder/MtomPart.cs]: Could you remove the `parsedValue` declaration, and change the out value to `out var parsedValue` to tidy things up a bit

File: src/WcfCoreMtomEncoder/MtomPart.cs [hunk 2]
```diff
@@ -32,7 +45,8 @@ public byte[] GetRawContent()
 
         public string GetStringContentForEncoder(MessageEncoder encoder)
         {
-            if (!ContentType.Parameters.Any(p => p.Name == "type" && encoder.IsContentTypeSupported(p.Value.Replace("\"", ""))))
+            if (ContentType == null ||
```
Comment (lennykean) [inline src/WcfCoreMtomEncoder/MtomPart.cs]: For readability sake, I'd prefer braces around the if body when the conditional spans multiple lines

**Review by lennykean — CHANGES_REQUESTED** [review]

File: src/WcfCoreMtomEncoder/MtomPart.cs (hunk 1 above)
Comment (lscorcia) [reply src/WcfCoreMtomEncoder/MtomPart.cs]: Sure!

File: src/WcfCoreMtomEncoder/MtomPart.cs (hunk 2 above)
Comment (lscorcia) [reply src/WcfCoreMtomEncoder/MtomPart.cs]: Sure!

**Review by lennykean — APPROVED** [review]
This looks great, Thanks!
